# Dependabot configuration for automated dependency updates
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    # Group all Python updates together to reduce PR noise
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    reviewers:
      - "francis-io/developers"  # Update with your team

  # Docker dependencies (Home Assistant image)
  - package-ecosystem: "docker"
    directory: "/tests/e2e/docker"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "francis-io/developers"  # Update with your team

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "francis-io/developers"  # Update with your team