# Minimal Home Assistant Configuration - Bypass Onboarding
homeassistant:
  name: Home
  latitude: 40.7128
  longitude: -74.0060
  elevation: 10
  unit_system: metric
  time_zone: UTC
  country: US
  internal_url: "http://localhost:8123"

  # Trusted networks authentication - no password required from these networks
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1       # localhost
        - ::1             # IPv6 localhost
        - 172.16.0.0/12   # Docker default network range
        - 192.168.0.0/16  # Common local network range
      allow_bypass_login: true
    - type: homeassistant  # Keep as fallback for external access

# Minimal components - comment out default_config to avoid unnecessary components
# default_config:

# Core components only
config:
system_health:
logger:
  default: warning

# API access (required for many operations)
api:

# Frontend (required to access the UI)
frontend:

# Required for the onboarding process
onboarding:
